[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:openplc_runtime]
command=python3 /opt/openplc/plc/openplc_runtime.py --process cooling --port 502
autostart=true
autorestart=true
stderr_logfile=/var/log/openplc_err.log
stdout_logfile=/var/log/openplc_out.log
